### ISSUE TITLE
Check for v8.7.0 or greater in agent for v3 instrumentation

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic-aws-sdk#117]
## Is your feature request related to a problem? Please describe.
In v8.6.0 we introduce `onResolved` hook to get the v3 of aws-sdk instrumentation working.  However we found and fixed a bug https://github.com/newrelic/node-newrelic/pull/986 which was released in v8.7.0.  In order to avoid tricky support issues, we should semver check the agent `>=8.7.0` before registering the v3 aws instrumentation.

**Comment by DavidRigglemanININ** [comment]
This change seems to have broke my code upon upgrading. Specifically, I'm now getting the following error when running my tests
```
TypeError: Cannot read property 'logger' of undefined
      17 | }
      18 |
    > 19 | require("@newrelic/aws-sdk");
         | ^

      at Object.<anonymous> (node_modules/@newrelic/aws-sdk/index.js:24:17)
      at Object.<anonymous> (src/core/metrics/NewRelic.ts:19:1)
```
If I manually install @newrelic/aws-sdk and force it to 4.0.1 (which I shouldn't have to do per the docs), the error goes away.

**Comment by garbados** [comment]
Thanks for reporting this issue, @DavidRigglemanININ . I'm reopening this issue while we look into it.

**Comment by bizob2828** [comment]
@DavidRigglemanININ do you know which version of `@newrelic/aws-sdk` is throwing that error? We did have an issue that we have since patched in `4.1.1` https://github.com/newrelic/node-newrelic-aws-sdk/issues/121

**Comment by DavidRigglemanININ** [comment]
4.1.1 was throwing the error for me.

**Comment by bizob2828** [comment]
@DavidRigglemanININ do you mind throwing together a repro case? I can't seem to reproduce by just adding `require('@newrelic/aws-sdk')`.

**Comment by DavidRigglemanININ** [comment]
I'm not really doing anything else other than the require. Is it possible this could be environment specific. For example, I am running NodeJs 14. Is it possible this error only surfaces in older versions of Node?

**Comment by DavidRigglemanININ** [comment]
Actually, I just realized I might now what is going on. I'm hitting this error in tests and I have some mocking set up with jest for the newrelic calls. I might now need to add the logger call as something I mock. I have test code that is setup as follows.
```
module.exports = {
    instrumentConglomerate: jest.fn(), // used by @newrelic/aws-sdk
    setLambdaHandler: callback => callback,
    noticeError: jest.fn(),
    recordCustomEvent: jest.fn()
};
```

**Comment by DavidRigglemanININ** [comment]
I confirmed I was able to fix my tests by adding the following
```
shim: { logger: { warn: jest.fn() } }, // used by @newrelic/aws-sdk
```
Maybe there's a better way to mock the require but it at least explains the issue and what was going on.

**Comment by bizob2828** [comment]
Oh your mock needed updated. Yea we pulled in the logger from agent to log warnings. This makes sense. I'm going to re-close this issue. Glad you figured it out!
