### ISSUE TITLE
Newrelic cannot start when instantiating several SNS clients 

### ISSUE THREAD

**Issue by DanielAnfelt** [newrelic/node-newrelic-aws-sdk#130]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
We are using newrelic to monitor a service which integrates with aws using the aws v3 sdk. Among others, it creates a set of SNSClients.
When upgrading the newrelic dependency to 8.8.0, we also got @newrelic/aws-sdk version 4.1.2

After that upgrade, newrelic could no longer start.
We got the stacktrace 
```
stack:  Error: Duplicate middleware name 'NewRelicSnsMiddleware'
    at Object.add (/usr/app/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:127:31)
    at Object.applyToStack (/usr/app/node_modules/@newrelic/aws-sdk/lib/v3/sns.js:33:19)
    at Object.use (/usr/app/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:164:20)
    at SNSClient.wrapShim (/usr/app/node_modules/@newrelic/aws-sdk/lib/v3/util.js:33:26)
    at SNSClient.wrappedReturn (/usr/app/node_modules/@newrelic/aws-sdk/lib/v3/util.js:53:27)
    at Object.constructTrap [as construct] (/usr/app/node_modules/newrelic/lib/shim/shim.js:654:29)
    at new PubSub (/usr/app/node_modules/@springworks/isapi-trips-v2/node_modules/@springworks/sns-pubsub/build/pub-sub.js:49:20)
    at new TripsV2PubSub (/usr/app/node_modules/@springworks/isapi-trips-v2/build/main.js:23:9)
    at Object.<anonymous> (/usr/app/build/api/processing/trips-events/trips-v2-events-publisher.js:10:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14) 
```

## Expected Behavior

newrelic should have started as usual

## Steps to Reproduce

I would assume that instantiating two sns clients through the aws v3 sdk, while running newrelic with aws-sdk support should be enough, but I didn't do any minimal project to verify that.

## Your Environment
My regular MacBook Pro. I don't think cpu or environment are relevant to the issue.

## Additional context
Our "workaround" was to downgrade the dependency of newrelic to 8.7.0 AND adding
```  
"resolutions": {
    "@newrelic/aws-sdk": "4.0.1"
  },
```
to the package.json

Another "workaround" was to go into the actual newrelic-aws-sdk library and rewrite the way the middleware was registered.

What we did was to edit "node_modules/@newrelic/aws-sdk/lib/v3/sns.js" and change the implementation of applyToStack slightly, by adding the override option

```
      clientStack.add(snsMiddleware.bind(null, shim), {
        name: 'NewRelicSnsMiddleware',
        step: 'initialize',
        priority: 'high',
        override: true, // manually added by a desperate developer
      })
```
Not sure if that makes any sense with regards to what an override is, but it allowed the NewRelicSnsMiddleware to be repeatedly registered without issues.

**Comment by bizob2828** [comment]
Thanks for logging this @DanielAnfelt.  Looks like you found an edge case we were not anticipating.  I'll take a look later and open a PR for a fix. I think overriding would be ok but I want to see if there are other options.

**Comment by bizob2828** [comment]
@DanielAnfelt can you provide a code snippet to reproduce this error? It looks like you may be wrapping the instantiation of the SNSClient in `@springworks/sns-pubsub/build/pub-sub.js`.  I tried a few scenarios and cannot recreate the error

```js
const { SNSClient } = require('@aws-sdk/client-sns')

**Comment by bizob2828** [comment]
@DanielAnfelt just checking in here.  can you provide a code snippet to reproduce this error?

**Comment by DanielAnfelt** [comment]
@bizob2828 Hi, sorry for not responding. It got lost in the barrage of notifications.

I've tried hard to come up with a way to reproduce this error. I can reproduce it, but I have no idea how or why. I get the error, then I comment out a few instantiations of the SNSClient and it works again. I'm not even sure it's a bug in the newrelic module anymore. I say we close this bug and should I ever be able to figure out why this is happening to me, I can come back with more info.

The setup I'm running (when having the issue) is a true mess of packages that depend on packages that have classes which wrap the client. Very sad to say that I give up, but the last 2 hours didn't bring me any closer to understanding what is going on.

**Comment by bizob2828** [comment]
Ok sounds good. Thanks for getting back to me
