### ISSUE TITLE
Spans not record DynamoDB response code

### ISSUE THREAD

**Issue by Blankll** [newrelic/node-newrelic-aws-sdk#146]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
We instrumented DynamoDB client in an AWS lambda by using official NewRelic-AWS-Lambda-Layers, In DynamoDB call Spans, it did not record the execution result of this call, We hope NewRelic can record DynamoDB execution results in Spans like HTTP calls which record both HTTP status code & message. 

Since DynamoDB call is also an HTTP call, We think it make sense to record response code and message in span as well.

## Expected Behavior
For any external call, we can get duration(exists),  code(for example: HTTP => status code, MySQL => code), message in the Span.
that can benefit:
1. calculate individual external call error_rate, based on status code, message and etc.
2.  error code & message not eliminated in Spans data set due to the [error span collection strategy](https://docs.newrelic.com/docs/distributed-tracing/ui-data/understand-use-distributed-tracing-ui#error-tips)

## Your Environment

env: AWS-lambda
Runtime: node-16
NewRelic-AWS Lambda-Layers: `arn:aws:lambda:ap-southeast-2:451483290750:layer:NewRelicNodeJS16X:16`
dependencies:
```json
{
   "@aws-sdk/client-dynamodb": "^3.128.0",
    "@aws-sdk/lib-dynamodb": "^3.128.0",
     "apollo-datasource": "^3.3.2",
    "apollo-server-lambda": "^3.10.1",
    "@newrelic/apollo-server-plugin": "^2.0.1"
}
```

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jordigh** [comment]
Probably related to https://github.com/newrelic/newrelic-node-apollo-server-plugin/issues/215, let's see if support.newrelic.com can help.

**Comment by bizob2828** [comment]
Hi @Blankll that's not something we typically put on database spans.  With that being said I'm talking internally to see how you could create queries to do this kind of discovery for your dynamo queries.

**Comment by bizob2828** [comment]
@Blankll have you tried the [AWS DynamoDB monitoring integration](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-dynamodb-monitoring-integration/)?  It creates metrics around specific errors which can help you answer your questions you had.

**Comment by Blankll** [comment]
Hi @bizob2828 , that true both DynamoDB metrics and AwsLambdaInvocationError have recorded the DynamoDB error, but our requirement is that we need to calculate the external call error rate and build the alert based on that, the external call record store in AwsLambdaInvocation, and error in AwsLambdaInvocationError, said, the alert NRQL does not support subquery, which means only we have DynamoDB execute result in Span like HTTP, we can achieve that.

**Comment by bizob2828** [comment]
I'm closing as the suggestion for getting the information needed would be in the AWS Dynamo monitoring integration
