### ISSUE TITLE
aws-sdk v3 instrumentation is crashing in versions >= 3.290.0

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic-aws-sdk#168]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

It looks like aws-sdk v3 updated their code to [lower case all header names](https://github.com/aws/aws-sdk-js-v3/pull/4450/files).  This crashes our instrumentation because we assign a symbol that is used to [disable distributed tracing](https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentation/core/http-outbound.js#L146).  It appears we have always had this behavior from the [start](https://github.com/newrelic/node-newrelic/commit/e091c259c#diff-9c7ed5295cbd385d88863e1b818dfdba424aacdeb5ddb365a11b3cd7dc7e47d8).  

## Expected Behavior

Aws sdk v3.290.0 should not crash and properly record spans for aws calls.

## Steps to Reproduce
`npm run versioned:major`

**Comment by kuhe** [comment]
The AWS SDK for JS v3 is planning to revert the change that is incompatible with Symbols, but I would still suggest going ahead with the change where you use string key and string value headers for future compatibility.

**Comment by bizob2828** [comment]
> The AWS SDK for JS v3 is planning to revert the change that is incompatible with Symbols, but I would still suggest going ahead with the change where you use string key and string value headers for future compatibility.

We plan on shipping a fix for this today.  It's just more involved because changes in this package(@newrelic/aws-sdk) and the agent(newrelic) are required.  We had this business logic for years and I'm not sure why we decided to add a Symbol to the headers object. My only guess is so our customers couldn't just set this header but that's on them.  We end up removing the header before the request goes over the wire anyways.
