### ISSUE TITLE
AWS SDK v3 DynamoDB - newrelic@11.0.0 (v7.0.0 of this lib) no longer record DynamoDB on Databases APM tab

### ISSUE THREAD

**Issue by huntharo** [newrelic/node-newrelic-aws-sdk#208]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

- See detailed notes and reproducible example here: https://github.com/pwrdrvr/dynamodb-session-store/pull/19
- DynamoDB access using `newrelic@10.4.0` logs DB access on the Database tab of APM, logging the specific operations, rates, and times
- DynamoDB access using `newrelic@11.0.0` logs DB access only as External Services of APM
- This PR appears to be a candidate of why this changed (but does not note this as intentional) as it removed the `lib-dynamodb` and `client-dynamodb` instrumentation and shifted the responsibility entirely to `smithy-client`: https://github.com/newrelic/node-newrelic-aws-sdk/pull/205

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

- DynamoDB access should be logged in detail on the Database tab of APM

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

- See full details and logs: https://github.com/pwrdrvr/dynamodb-session-store/pull/19

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

- See full reproduction steps and code on an open source project that demos this: https://github.com/pwrdrvr/dynamodb-session-store/pull/19

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Node version: 16.17.1
* Operating System and version: Mac OS X and `node:18.17-alpine3.18` Docker image

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment]
Hi @huntharo a support rep here brought this to our attention.  Thanks for the repro case, it will make it easier to triage this issue.  Sorry for the troubles

**Comment by bizob2828** [comment]
Ok, I see the issue.  When we moved our instrumentation from instrumenting `@aws-sdk/lib-dynamodb` and `@aws-sdk/client-dynamodb`, we neglected to include checking for a class that gets exported in `@aws-sdk/lib-dynamodb` `DynamoDBDocument`.  Your wrapper code creates a client from that [here](https://github.com/pwrdrvr/dynamodb-session-store/blob/main/src/dynamodb-store.ts#L341).

**Comment by bizob2828** [comment]
@huntharo the fix for this has been released in 7.0.1

**Comment by huntharo** [comment]
> @huntharo the fix for this has been released in 7.0.1

Thank you!  Yup, I have confirmed in my test case app that the issue was resolved and just deployed this to Prod in our app that was using this and confirmed it was resolved there as well with `7.0.1`.  Thanks!
