### ISSUE TITLE
Geting Duplicate middleware name 'NewRelicHeader' with DynamoDb client BatchWriteItemCommand

### ISSUE THREAD

**Issue by michael-anodot** [newrelic/node-newrelic-aws-sdk#211]
## Description

using:
"newrelic": "^11.0.0"
"@aws-sdk/client-dynamodb": "3.363.0"
"@smithy/util-retry": "^2.0.0"

My Code is:
```
const { DynamoDBClient, CreateBackupCommand, BatchWriteItemCommand } = require('@aws-sdk/client-dynamodb');
const { ConfiguredRetryStrategy } = require('@smithy/util-retry');
...
this.DYNAMODB_CLIENT = new DynamoDBClient({
      region: regionId || 'us-east-1',
      retryStrategy: new ConfiguredRetryStrategy(
        6, // max attempts.
        (attempt) => 100 + attempt * 1250, // backoff function.
      ),
    });
...
await this.DYNAMODB_CLIENT.send(new BatchWriteItemCommand(params));
```

when calling await this.DYNAMODB_CLIENT.send(new BatchWriteItemCommand(params))
Getting:
```
Error: Duplicate middleware name 'NewRelicHeader'
    at Object.add (/Users/michaelgreenwald/WebstormProjects/Cost/frontend-app-server/node_modules/@smithy/middleware-stack/dist-cjs/MiddlewareStack.js:130:31)
    at DynamoDBClient.wrappedSend (/Users/michaelgreenwald/WebstormProjects/Cost/frontend-app-server/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:49:30)
    at DynamoDbClient.executeBatchWrite (/Users/michaelgreenwald/WebstormProjects/Cost/frontend-app-server/modules/dynamoDbClient.js:119:41)
    at DynamoDbClient.batchWrite (/Users/michaelgreenwald/WebstormProjects/Cost/frontend-app-server/modules/dynamoDbClient.js:140:37)
    at /Users/michaelgreenwald/WebstormProjects/Cost/frontend-app-server/invoices/query-cache/db-query-cache.model.js:216:28
    at Array.map (<anonymous>)
    at DbQueryCache.cacheQueryData (/Users/michaelgreenwald/WebstormProjects/Cost/frontend-app-server/invoices/query-cache/db-query-cache.model.js:215:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Tried to upgrade to the latest version of aws-sdk, and got the same error
Tried to downgrade newrelic to version 10.5.0 as described in https://github.com/newrelic/node-newrelic/issues/1688#issuecomment-1644853787 - with this version, I got the same error on the server init instead of when calling the await this.DYNAMODB_CLIENT.send(new BatchWriteItemCommand(params)) line

## Your Environment

node: 18.16.1
"newrelic": "^11.0.0"
"@aws-sdk/client-dynamodb": "3.363.0"
"@smithy/util-retry": "^2.0.0"

**Comment by bizob2828** [comment]
@michael-anodot I cannot reproduce with little information you provided.  If you can provide a full reproduction case, please link it.  But I suspect your issue might be what @mrickard mentioned above.

**Comment by michael-anodot** [comment]
@bizob2828, @mrickard ,
This is why I have in the package-lock file:
```
"node_modules/@newrelic/aws-sdk": {
      "version": "7.0.0",
      "resolved": "https://registry.npmjs.org/@newrelic/aws-sdk/-/aws-sdk-7.0.0.tgz",
      "integrity": "sha512-/14Y9qYomDEzFrdXogqms2CGMI9hEJECzNBSqBLT53FY/uZh6SdI4Tr5u0sEOghjCdNyF2rseW7u63bAn09Pxw==",
      "engines": {
        "node": ">=16.0.0"
      },
      "peerDependencies": {
        "newrelic": ">=10.0.0"
      }
    },
```
And this is the only instance of this package in the file

**Comment by bizob2828** [comment]
@michael-anodot this is only out of date by a patch release, but shouldn't exhibit the issues we saw with aws sdk in the past.  A full reproduction case will be necessary for us to triage this.

**Comment by michael-anodot** [comment]
@bizob2828, @mrickard ,
Please note that I was able to bypass the problem by switching from DynamoDBClient to DynamoDBDocumentClient
any idea why this will make a difference?

**Comment by bizob2828** [comment]
@michael-anodot I do not, but if you can provide the reproduction case, I could tell you for certain.
