### ISSUE TITLE
Memory exhaustion in newrelic/lib/util/logger.js when using @aws-sdk/client-sqs

### ISSUE THREAD

**Issue by yehor-manzhula** [newrelic/node-newrelic-aws-sdk#218]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
After updating newrelic to version 11.6.0 client we faced with memory leaks issues in our code that uses @aws-sdk/client-sqs.
I've created a [repository](https://github.com/yehor-manzhula/newrelic-memory-leak) with an example that reproduces the issue we faced. (Please follow readme.me to startup project)

Right after test script `./run.sh ./src/aws-sdk-gc.js` is started memory starts rasing dramatically fast.
I've analyze the heapdumps and found that there are bunch of identical object being added in the snapshot comparison that route me to newrelic/lib/util/logger.js (see screenshots)

![newrelic logger memory leak](https://github.com/newrelic/node-newrelic/assets/5948294/acded96a-8af0-4f6f-940e-e5e6f300fb80)

## Expected Behavior
Memory will be cleaned with GC.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
1. Clone example [repository](https://github.com/yehor-manzhula/newrelic-memory-leak) 
2. Follow readme.md
3. Run test script `./run.sh ./src/aws-sdk-gc.js`

## Your Environment
* ex: Node version: 20.10.0
* ex: Operating System and version: Linux Ubuntu 22.04.3 LTS

**Comment by jsumners-nr** [comment]
I concur that this is not likely a "leak." The structure of the reproduction is such that it creates an infinite number of promises to be resolved. Individual promises are expensive; an unbounded set of promises is extremely expensive. I would recommend polling SQS in a more event loop friendly way. https://github.com/jsumners/sqsiphon/blob/11bffb23efb52ce5f0f1088f4abac84f7d60ea9b/index.js may provide some insight.

**Comment by bizob2828** [comment]
@yehor-manzhula this went out at 7.0.3 of `@newrelic/aws-sdk`. Can you do a fresh install of the `newrelic` agent and let me know how it goes?
