### ISSUE TITLE
Bedrock: Remove `response.usage.completion_tokens`, `response.usage.total_tokens`, `response.usage.prompt_tokens` from LlmEmbedding and LlmChatCompletionSummary

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic-aws-sdk#265]
### Description
Once the AIM UI has been updated to read token counts from `token_count` key(see #264 ), we should remove the legacy attributes `response.usage.completion_tokens`, `response.usage.total_tokens`, and `response.usage.prompt_tokens`.
We also want to remove transaction_id from all events as it will no longer be necesary as events will be queried by trace_id

**Comment by jsumners-nr** [comment]
See https://github.com/newrelic/node-newrelic-aws-sdk/pull/269
