### ISSUE TITLE
Publish new version with amazon-dax-client fix

### ISSUE THREAD

**Issue by MatthiasVervaet** [newrelic/node-newrelic-aws-sdk#32]
Is there an eta of when the fix described here: https://github.com/newrelic/node-newrelic-aws-sdk/commit/f193b36a7d2dd2136f802d2079abd2f3f8829b28 will be published as a new version of this library?

**Comment by michaelgoin** [comment]
Hi @MatthiasVervaet,

A new version has just been published. You can leverage right away by manually installing version `1.1.2` locally. We will also be rolling this version into the main agent soon.

Thanks,

Michael
