### ISSUE TITLE
Add footer to third party notices

### ISSUE THREAD

**Issue by carlonewrelic** [newrelic/node-newrelic-aws-sdk#62]
Add footer to third party notices as seen in agent tpm:
https://github.com/newrelic/node-newrelic/blob/main/THIRD_PARTY_NOTICES.md

**Comment by michaelgoin** [comment]
Is this meant to still be open or has a PR already landed for this?

**Comment by carlonewrelic** [comment]
> Is this meant to still be open or has a PR already landed for this?

PR landed
