### ISSUE TITLE
Add GitHub Actions Badges to README.md

### ISSUE THREAD

**Issue by astormnewrelic** [newrelic/node-newrelic-aws-sdk#66]
Add GitHub Actions Badges to README.md once this repos CI is moved over to GitHub Actions.

**Comment by michaelgoin** [comment]
While in here, would remove reference to AWS secrets in readme.

**Comment by michaelgoin** [comment]
Also: fix misspelling of "project" (projet) and remove the "remove this section if it's not needed" language.
