### ISSUE TITLE
dynamodb: batchGet, batchWrite, transactWrite, and transactGet are not tracked in database instrumentation

### ISSUE THREAD

**Issue by TysonAndre** [newrelic/node-newrelic-aws-sdk#83]
## Summary

Operations such as getItem and putItem are tracked for dynamodb, but batchGet, batchWrite, etc. are not tracked at all in the datastore tab

## Desired Behavior

Track the average duration and throughput of batchGet, batchWrite, transactWrite, and transactGet 

## Possible Solution

```patch
--- a/lib/dynamodb.js
+++ b/lib/dynamodb.js
@@ -20,6 +20,10 @@ const DOC_CLIENT_OPERATIONS = [
   'put',
   'update',
   'delete',
+  'batchGet',
+  'batchWrite',
+  'transactGet',
+  'transactWrite',
   'query',
   'scan'
 ]
```

It seems like the serviceClientOperationsMap required by `@newrelic/aws-sdk` is available in the latest aws-sdk - I haven't checked if older sdks are different

```js
// node_modules/aws-sdk/lib/dynamodb/document_client.js
  /**
   * @api private
   */
  serviceClientOperationsMap: {
    batchGet: 'batchGetItem',
    batchWrite: 'batchWriteItem',
    delete: 'deleteItem',
    get: 'getItem',
    put: 'putItem',
    query: 'query',
    scan: 'scan',
    update: 'updateItem',
    transactGet: 'transactGetItems',
    transactWrite: 'transactWriteItems'
  },

```

## Additional context

Providing this information gives us an accurate idea of the way an application and transaction uses batch writes and gets.

It seems as if uninstrumented API calls get reported as a call to `External service: dynamodb.us-east-1.amazonaws.com:443` in the external services tab instead

**Comment by michaelgoin** [comment]
Hi @TysonAndre,

Thank you for the request. We'll track and prioritize this against our other work. If you (or someone else viewing this issue) are interested, we also welcome PRs for those who want to take stab at a solution.

One thing to keep in mind is for some libraries (maybe not in this case) batch function calls can trigger other instrumentation which we have to be careful with. These AWS client functions tend to be wrappers on web API methods, so I'm guessing would not be the case here.

**Comment by TysonAndre** [comment]
> It seems as if uninstrumented API calls get reported as a call to External service: dynamodb.us-east-1.amazonaws.com:443 in the external services tab instead

I updated the ticket after the initial comment - for me, it seems like there were 60k throughput of DynamoDB getItem before the refactoring, and 28K external calls to dynamodb.us-east-1.amazonaws.com in the "External services" call after refactoring to call batchGet, and the reduction was intended. The other 3 methods weren't used.

> These AWS client functions tend to be wrappers on web API methods, so I'm guessing would not be the case here.

I'd guess the same

**Comment by TysonAndre** [comment]
```
  batchGet: function(params, callback) {
    var operation = this.serviceClientOperationsMap['batchGet'];
    return this.makeServiceRequest(operation, params, callback);
  },
  batchWrite: function(params, callback) {
    var operation = this.serviceClientOperationsMap['batchWrite'];
    return this.makeServiceRequest(operation, params, callback);
  },
  transactWrite: function(params, callback) {
    var operation = this.serviceClientOperationsMap['transactWrite'];
    return this.makeServiceRequest(operation, params, callback);
  },
  transactGet: function(params, callback) {
    var operation = this.serviceClientOperationsMap['transactGet'];
    return this.makeServiceRequest(operation, params, callback);
  },
```
node_modules/aws-sdk/lib/dynamodb/document_client.js is not doing anything unusual in https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/document_client.js#L205-L208

**Comment by TysonAndre** [comment]
And the oldest supported version from newrelic-aws-sdk 2.403.0 is also the same implementation and has all 4 operations
https://github.com/aws/aws-sdk-js/blob/v2.403.0/lib/dynamodb/document_client.js#L157-L476
