### ISSUE TITLE
Feature request: Supporting AWS SDK v3

### ISSUE THREAD

**Issue by TysonAndre** [newrelic/node-newrelic-aws-sdk#86]
## Is your feature request related to a problem? Please describe.
AWS SDK for JavaScript, version 3 (v3) became generally available 2 months ago (December 2020), see https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available/ 

v3 of the aws sdk includes features that may motivate users to switch to it, such as:
- Being modular instead of one large bundle to reduce download/installation sizes
- HTTP keepalive was enabled by default, significantly improving default performance
- HTTP/2 support was introduced, to multiplex requests over connections instead of needing to maintain multiple HTTPS HTTP 1.1 connections to AWS's servers (e.g. useful if there is a large volume of requests to a backend service that supports http/2),
  (I'd assume that this would result in better performance if http/2 was supported but may be mistaken; I haven't found any benchmarks or switched yet)
  
  EDIT: HTTP/2 is supported but not enabled by default, it looks like an end user would have to pass `requestHandler: NodeHttp2RequestHandler` in the options override object, and there are still some open bugs in their HTTP/2 support in https://github.com/aws/aws-sdk-js-v3/issues?q=is%3Aissue+is%3Aopen+NodeHttp2Handler

  EDIT: I'm personally delaying upgrading to v3 for reasons unrelated to newrelic

  EDIT: HTTP/2 is currently only supported by AWS backends for a small number of services. See https://github.com/aws/aws-sdk-go/issues/2984 (from 2019)
 

At a glance, this instruments `require('aws-sdk')` , but not `@aws-sdk/modulename` (e.g. `@aws-sdk/client-dynamodb`).

## Feature Description

Instrument aws-sdk-v3 components such as dynamodb as a datastore instead of an external service call. (I confirmed it currently shows up as an external service call to the aws hostname in newrelic)

This may make sense as a separate repo such as newrelic/node-newrelic-aws-sdk-v3 to be independently developed

## Describe Alternatives

It should be possible for end users of newrelic to use newrelic's custom datastore instrumentation to instrument aws-sdk v3 as a custom datastore for dynamodb - I haven't started working on that but should be able to figure it out.

## Additional context

https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/dynamodb-example-table-read-write.html has an example snippet of v3 dynamodb, and https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/sdk-code-samples.html has various API references for the AWS SDK v3 that may be useful in understanding how v3 differs from v2

## Priority

Nice to have

**Comment by michaelgoin** [comment]
Thank you for the feature request and detailed notes. I'll make sure this is visible to our PM for consideration and prioritization.

**Comment by artur-ma** [comment]
@michaelgoin Any updates on this? Thanks

**Comment by michaelgoin** [comment]
@artur-ma no updates, currently. But if this is something you are also interested in, I would recommend putting a 👍 on the issue which will provide additional input for helping our PM prioritize against other work.

**Comment by bizob2828** [comment]
[Notes](https://docs.google.com/document/d/15I2MD1yjUlDFAkgchSQlTolLJAltMPpmKsdgusCWa_g/edit?usp=sharing) from research in May 2021

**Comment by bizob2828** [comment]
[Project Board](https://github.com/orgs/newrelic/projects/58/views/1)

**Comment by bizob2828** [comment]
This was addressed in [v4.1.0](https://github.com/newrelic/node-newrelic-aws-sdk/releases/tag/v4.1.0).  

**NOTE**: You must upgrade agent to v8.7.0 for it to register the instrumentation for aws sdk v3
